{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?file ?bytes
WHERE {
  GRAPH <{{state_graph}}> {

    ?container      rdf:type                      shst:DatasetContainer .
    ?container      shst:account                  <account:{{account_uuid}}> .

    {
      ?container    shst:draft                    ?dataset .
    } UNION {
      ?container    shst:published_versions/rdf:rest*/rdf:first ?dataset .
    }

    ?dataset        rdf:type                      shst:Dataset .
    ?dataset        shst:files/rdf:rest*/rdf:first ?file .

    ?file           rdf:type                      shst:File .
    ?file           shst:size                     ?bytes .
  }
}
{% endblock %}
