{% extends "prefixes.sparql" %}
{% block query %}
PREFIX author: <{{author_uri}}>
SELECT DISTINCT ?id         ?full_name       ?first_name  ?last_name
                ?group_id   ?institution_id  ?is_active   ?is_public
                ?job_title  ?orcid_id        ?account     ?categories
                ?location   ?twitter         ?linkedin    ?website
                ?image      ?account_uuid    ?biography
WHERE {
  GRAPH <{{state_graph}}> {
    author:            shst:is_active           ?is_active ;
                       shst:is_public           ?is_public ;
                       shst:full_name           ?full_name .
    OPTIONAL { author: shst:id                  ?id . }
    OPTIONAL { author: shst:account             ?account . }
    OPTIONAL { author: shst:first_name          ?first_name . }
    OPTIONAL { author: shst:last_name           ?last_name . }
    OPTIONAL { author: shst:group_id            ?group_id . }
    OPTIONAL { author: shst:institution_id      ?institution_id . }
    OPTIONAL { author: shst:job_title           ?job_title . }
    OPTIONAL { author: shst:orcid_id            ?orcid_id . }
    OPTIONAL { author: shst:account             ?account .
               OPTIONAL { ?account shst:location           ?location . }
               OPTIONAL { ?account shst:twitter            ?twitter . }
               OPTIONAL { ?account shst:linkedin           ?linkedin . }
               OPTIONAL { ?account shst:website            ?website . }
               OPTIONAL { ?account shst:categories         ?categories . }
               OPTIONAL { ?account shst:biography          ?biography . }
               OPTIONAL { ?account shst:profile_image      ?image . }
               BIND(STRAFTER(STR(?account), ":") AS        ?account_uuid)
    }
  }
}
{% endblock %}
