{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?id ?uuid ?parent_id ?parent_uuid ?title ?source_id ?taxonomy_id ?classification_code
WHERE {
  GRAPH <{{state_graph}}> {
    ?category         rdf:type                           shst:Category ;
                      shst:id                            ?id ;
                      shst:title                         ?title .
    OPTIONAL {
      ?category        shst:parent_id                    ?parent_id .
      ?parent_category shst:id                           ?parent_id .

      BIND(STRAFTER(STR(?parent_category), "category:") AS ?parent_uuid)
    }
    OPTIONAL { ?category  shst:classification_code       ?classification_code . }
    OPTIONAL { ?category  shst:source_id                 ?source_id . }
    OPTIONAL { ?category  shst:taxonomy_id               ?taxonomy_id . }
    {%- if item_uri is not none %}
    ?item_uri        shst:categories/rdf:rest*/rdf:first ?category .
    {%- if account_uuid is not none %}
    ?container         rdf:type/rdfs:subClassOf         shst:Container .
    ?container         shst:account                     ?account .
    {%- if is_published %}
    ?container         shst:published_versions/rdf:rest*/rdf:first ?item_uri .
    {%- else %}
    ?container         shst:draft                        ?item_uri .
    {%- endif %}
    {%- if not disable_collaboration %}
    OPTIONAL {
      ?collaborator      rdf:type            shst:Collaborator .
      ?collaborator      shst:item           ?item_uri .
      ?collaborator      shst:account        ?collaborator_account .
      ?collaborator      shst:metadata_read  "true"^^xsd:boolean .
    }
    OPTIONAL {
      ?group_uri          rdf:type shst:InstitutionGroup .
      ?item_uri           shst:association_criteria        ?association_criteria .
      ?group_uri          shst:association_criteria        ?association_criteria .
      ?group_uri          shst:members/rdf:rest*/rdf:first ?member_uri .
      ?member_uri         shst:is_supervisor "true"^^xsd:boolean .
      ?member_uri         shst:account ?member_account .
    }
    {%- endif %}
    {%- endif %}
    {%- endif %}

    BIND(STRAFTER(STR(?category), "category:") AS ?uuid)
  }
{%- if account_uuid is not none %}
  {%- if disable_collaboration %}
  FILTER (?account = <account:{{account_uuid}}>)
  {%- else %}
  FILTER (?account = <account:{{account_uuid}}> ||
          ?collaborator_account = <account:{{account_uuid}}>)
  {%- endif %}
{%- endif %}
{%- if item_uri is not none %}
  FILTER (?item_uri = <{{item_uri}}>)
{%- endif %}
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
