{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?dataset_uri
                ?metadata_read      ?metadata_edit      ?metadata_remove
                ?data_read          ?data_edit          ?data_remove
                ?first_name         ?last_name          ?uuid
                ?email              ?order_index        ?account_uuid
                ?group_id           ?group_name         ?is_supervisor
                (?rest AS ?originating_blank_node)      ?is_inferred
WHERE {
  GRAPH <{{state_graph}}> {
    ?dataset_uri       shst:container/shst:account ?owner .
    {
      ?dataset_uri       shst:collaborators       ?collaborators .
      ?collaborators     rdf:rest*                ?rest .
      ?rest              rdf:first                ?collaborator_uri .
      ?rest              shst:index               ?order_index .
      ?collaborator_uri  rdf:type                 shst:Collaborator .
      ?collaborator_uri  shst:account             ?account .

      ?collaborator_uri  shst:metadata_read       ?metadata_read .
      ?collaborator_uri  shst:metadata_edit       ?metadata_edit .
      ?collaborator_uri  shst:metadata_remove     ?metadata_remove .
      ?collaborator_uri  shst:data_read           ?data_read .
      ?collaborator_uri  shst:data_edit           ?data_edit .
      ?collaborator_uri  shst:data_remove         ?data_remove .

      OPTIONAL {
        ?account           shst:domain              ?domain .
        ?group_uri         rdf:type                   shst:InstitutionGroup ;
                           shst:association_criteria  ?domain ;
                           shst:name                  ?group_name ;
                           shst:id                    ?group_id .
      }
      BIND("false"^^xsd:boolean AS ?is_inferred)
    }
    {%- if include_inferred %}
    UNION {
      ?group_uri         rdf:type shst:InstitutionGroup .
      ?dataset_uri       shst:association_criteria ?association_criteria .
      ?group_uri         shst:association_criteria ?association_criteria .
      ?group_uri         shst:members             ?members .
      ?group_uri         shst:name                ?group_name .
      ?group_uri         shst:id                  ?group_id .
      ?members           rdf:rest*                ?rest .
      ?rest              rdf:first                ?collaborator_uri .
      ?rest              shst:index               ?order_index .
      ?collaborator_uri  rdf:type                 shst:Member .
      ?collaborator_uri  shst:account             ?account .
      ?collaborator_uri  shst:metadata_read       ?metadata_read .
      ?collaborator_uri  shst:metadata_edit       ?metadata_edit .
      ?collaborator_uri  shst:metadata_remove     ?metadata_remove .
      ?collaborator_uri  shst:data_read           ?data_read .
      ?collaborator_uri  shst:data_edit           ?data_edit .
      ?collaborator_uri  shst:data_remove         ?data_remove .
      ?collaborator_uri  shst:is_supervisor       ?is_supervisor .

      BIND("true"^^xsd:boolean AS ?is_inferred)
    }
    {%- endif %}
    OPTIONAL { ?account           shst:first_name          ?first_name . }
    OPTIONAL { ?account           shst:last_name           ?last_name . }
    OPTIONAL { ?account           shst:email               ?email . }

    BIND(STRAFTER(STR(?collaborator_uri), ":") AS ?uuid)
    BIND(STRAFTER(STR(?account), "account:") AS ?account_uuid)

  }
FILTER (?owner != ?account)
FILTER (?dataset_uri = <dataset:{{dataset_uuid}}>)
{%- if account_uuid is not none %}
FILTER (?account = <account:{{account_uuid}}>)
{%- endif %}
}
{% endblock %}
