{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?name          ?value         ?default_value
                ?id            ?placeholder   ?max_length
                ?min_length    ?field_type    ?is_multiple
                ?is_mandatory
WHERE {
  GRAPH <{{state_graph}}> {
    ?field             rdf:type                 shst:CustomField .
    ?field             shst:original_name        ?name .
    ?field             shst:predicate            ?predicate .

    {%- if item_uri is not none %}
    ?item_uri          rdf:type                 shst:{{prefix}} ;
                       ?predicate               ?value .
    {%- endif %}
    OPTIONAL { ?field  shst:default_value        ?default_value . }
    OPTIONAL { ?field  shst:placeholder          ?placeholder . }
    OPTIONAL { ?field  shst:max_length           ?max_length . }
    OPTIONAL { ?field  shst:min_length           ?min_length . }
    OPTIONAL { ?field  shst:field_type           ?field_type . }
    OPTIONAL { ?field  shst:is_multiple          ?is_multiple . }
    OPTIONAL { ?field  shst:is_mandatory         ?is_mandatory . }
  }
  {#- Historically the "derived from" field could have multiple values, #}
  {#- so this has to be dealt with separately. #}
  FILTER (?predicate != shst:derived_from)
{%- if item_uri is not none %}
  FILTER (?item_uri = <{{item_uri}}>)
{%- endif %}
{%- if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
