{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?account    shst:group          ?group .
    ?group      ?predicate          ?object .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?account    rdf:type            shst:Account .
    ?account    shst:group          ?group .
  }
}
{% endblock %}
