{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?group      ?predicate          ?object .
    ?account    shst:group          ?group .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?group      rdf:type            shst:InstitutionGroup .
    ?group      shst:is_inferred    "true"^^xsd:boolean .
    ?group      ?predicate          ?object .

    OPTIONAL {
      ?account    rdf:type           shst:Account .
      ?account    shst:group         ?group .
    }
  }
}
{% endblock %}
