{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?collaborator_uri  shst:account             ?account .
    ?collaborator_uri  rdf:type                 shst:Collaborator .
    ?collaborator_uri  shst:metadata_read       ?metadata_read .
    ?collaborator_uri  shst:metadata_edit       ?metadata_edit .
    ?collaborator_uri  shst:metadata_remove     ?metadata_remove .
    ?collaborator_uri  shst:data_read           ?data_read .
    ?collaborator_uri  shst:data_edit           ?data_edit .
    ?collaborator_uri  shst:data_remove         ?data_remove .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?collaborator_uri  shst:account             ?account .
    ?collaborator_uri  rdf:type                 shst:Collaborator .
    ?collaborator_uri  shst:metadata_read       ?metadata_read .
    ?collaborator_uri  shst:metadata_edit       ?metadata_edit .
    ?collaborator_uri  shst:metadata_remove     ?metadata_remove .
    ?collaborator_uri  shst:data_read           ?data_read .
    ?collaborator_uri  shst:data_edit           ?data_edit .
    ?collaborator_uri  shst:data_remove         ?data_remove .
  }

FILTER (?collaborator_uri = <collaborator:{{collaborator_uuid}}>)
}
{% endblock %}
