{% extends "prefixes.sparql" %}
{% block query %}
SELECT DISTINCT ?uuid ?request_date ?reminder_date ?assigned_to
                ?account_uuid ?dataset_uuid ?dataset_title ?group_name
                ?submitter_first_name ?submitter_last_name ?submitter_email
                ?published_date ?container_uuid ?dataset_version ?declined_date
                ?reviewer_email ?reviewer_first_name ?reviewer_last_name
                ?modified_date (?status_label AS ?status) ?has_published_version
                ?last_seen_by_reviewer
WHERE {
  GRAPH <{{state_graph}}> {
    ?review             rdf:type                 shst:Review ;
                        shst:dataset              ?dataset .

    OPTIONAL { ?review  shst:request_date         ?request_date . }
    OPTIONAL { ?review  shst:reminder_date        ?reminder_date . }
    OPTIONAL {
      ?review           shst:status               ?status_uri .
      ?status_uri       rdfs:label                ?status_label .
    }

    ?dataset            shst:container            ?container_uri ;
                        shst:title                ?dataset_title .
    OPTIONAL { ?dataset shst:published_date       ?published_date . }
    OPTIONAL { ?dataset shst:declined_date        ?declined_date . }
    OPTIONAL { ?dataset shst:modified_date        ?modified_date . }
    OPTIONAL { ?dataset shst:last_seen_by_reviewer ?last_seen_by_reviewer . }
    OPTIONAL { ?dataset shst:version              ?dataset_version . }

    ?container_uri      shst:account              ?account .
    {%- if domain is not none %}
    ?account            shst:domain               "{{domain}}"^^xsd:string .
    {%- endif %}
    {%- if group_id is not none %}
    ?dataset            shst:group_id             {{group_id}} .
    {%- endif %}

    OPTIONAL { ?container_uri shst:latest_published_version ?published_version . }
    OPTIONAL {
      ?group            rdf:type                 shst:InstitutionGroup ;
                        shst:id                   ?group_id ;
                        shst:name                 ?group_name .
      ?dataset          shst:group_id             ?group_id .
    }

    OPTIONAL { ?account shst:email                ?submitter_email . }
    OPTIONAL { ?account shst:first_name           ?submitter_first_name . }
    OPTIONAL { ?account shst:last_name            ?submitter_last_name . }
    OPTIONAL { ?account shst:institution_id       ?institution_id . }

    OPTIONAL {
      ?review  shst:assigned_to          ?assigned_to .
      {#- OPTIONAL within OPTIONAL because if ?assigned_to is unbound,
       #- the following OPTIONAL bindings shouldn't just bind freely to anything
       #- with these predicates. #}
      OPTIONAL { ?assigned_to shst:email            ?reviewer_email . }
      OPTIONAL { ?assigned_to shst:first_name       ?reviewer_first_name . }
      OPTIONAL { ?assigned_to shst:last_name        ?reviewer_last_name . }
    }

    BIND(STRAFTER(STR(?container_uri), "container:") AS ?container_uuid)
    BIND(STRAFTER(STR(?dataset), "dataset:")  AS ?dataset_uuid)
    BIND(STRAFTER(STR(?account), "account:")  AS ?account_uuid)
    BIND(STRAFTER(STR(?review),  "review:")   AS ?uuid)
    BIND(BOUND(?published_version)            AS ?has_published_version)
  }
{%- if assigned_to is not none %}
  FILTER (?assigned_to = <account:{{assigned_to}}>)
{%- if review_uuid is not none: %}
  FILTER (?review = <review:{{review_uuid}}>)
{%- endif %}
{%- endif %}
{%- if status is not none %}
  FILTER (?status_uri = shst:Review{{status | safe}})
{%- endif %}
{% if filters is not none %}{{ filters | safe }}{% endif %}
}
{% endblock %}
