{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    {%- if requested_size is not none %}
    ?request          shst:requested_size        ?requested_size .
    {%- endif %}{% if reason is not none %}
    ?request          shst:reason                ?reason .
    {%- endif %}{% if status is not none %}
    ?request          shst:status                ?status .
    {%- if assign_to_account %}
    ?account          shst:quota                 ?quota .
    {%- endif %}
    {%- endif %}
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    {%- if requested_size is not none %}
    ?request          shst:requested_size        {{requested_size}} .
    {%- endif %}{% if reason is not none %}
    ?request          shst:reason                {{reason}} .
    {%- endif%}{% if status is not none %}
    ?request          shst:status                {{status | safe}} .
    {%- if assign_to_account %}
    {%- if requested_size is not none %}
    ?account          shst:quota                 {{requested_size}} .
    {%- else %}
    ?account          shst:quota                 ?requested_size .
    {%- endif %}
    {%- endif %}
    {%- endif %}
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?request              rdf:type                  shst:QuotaRequest .
    ?request              shst:account              ?account .
    OPTIONAL { ?account   shst:quota                ?quota . }
    OPTIONAL { ?request   shst:requested_size       ?requested_size . }
    OPTIONAL { ?request   shst:reason               ?reason . }
    OPTIONAL { ?request   shst:status               ?status . }
  }
  FILTER (?request = <quota-request:{{quota_request_uuid}}>)
}
{% endblock %}
