{% extends "prefixes.sparql" %}
{% block query %}
DELETE {
  GRAPH <{{state_graph}}> {
    ?container shst:total_downloads ?total_downloads .
    ?container shst:total_views ?total_views .
  }
}
INSERT {
  GRAPH <{{state_graph}}> {
    ?container shst:total_downloads ?downloads .
    ?container shst:total_views ?views .
  }
}
WHERE {
  GRAPH <{{state_graph}}> {
    ?container rdf:type shst:DatasetContainer .
    ?container shst:published_versions/rdf:rest*/rdf:first ?dataset .
    OPTIONAL { ?container shst:total_downloads    ?total_downloads . }
    OPTIONAL { ?container shst:total_views        ?total_views . }
    OPTIONAL { ?dataset   shst:embargo_until_date ?embargo_until_date . }
    OPTIONAL { ?dataset   shst:embargo_type       ?embargo_type . }
    {
      SELECT ?container (COUNT(?view) AS ?views)
      WHERE {
        GRAPH <{{state_graph}}> {
          ?view     rdf:type        shst:LogEntry .
          ?view     shst:event_type shst:LogEntryView .
          ?view     shst:dataset    ?container .
        }
      }
    }
    {
      SELECT ?container (COUNT(?download) AS ?downloads)
      WHERE {
        GRAPH <{{state_graph}}> {
          ?download rdf:type        shst:LogEntry .
          ?download shst:event_type shst:LogEntryDownload .
          ?download shst:dataset    ?container .
        }
      }
    }
    BIND(STRAFTER(STR(?container), "container:") AS ?container_uuid)
    BIND((BOUND(?embargo_until_date)  && ?embargo_until_date > NOW()) AS ?is_embargoed)
    BIND((!BOUND(?embargo_until_date) && BOUND(?embargo_type)) AS ?is_restricted)
  }
  FILTER (?is_embargoed = "false"^^xsd:boolean)
  FILTER (?is_restricted = "false"^^xsd:boolean)
}
{% endblock %}
